# Generated by Django 3.2.7 on 2021-10-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211013_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.AddField(
            model_name='product',
            name='long_desc',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='product',
            name='short_desc',
            field=models.CharField(default='', max_length=50),
        ),
    ]
