# Generated by Django 3.2.7 on 2021-10-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('array', models.JSONField(default=dict)),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=300)),
                ('address', models.CharField(default='', max_length=600)),
                ('e_mail', models.CharField(default='', max_length=400)),
                ('city', models.CharField(default='', max_length=70)),
                ('state', models.CharField(default='', max_length=70)),
                ('zip', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
